server.port=${PORT:8007}

# Brevo API Configuration
brevo.api.url=https://api.brevo.com/v3/smtp/email
brevo.api.key=${BREVO_API_KEY}
brevo.from.email=${MAIL_FROM:juandavidmn@ufps.edu.co}
brevo.from.name=${MAIL_FROM_NAME:microshop team}

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
