server.port=${PORT:8007}

# MailerSend API Configuration
mailersend.api.url=https://api.mailersend.com/v1/email
mailersend.api.token=${MAILERSEND_API_TOKEN}
mailersend.from.email=${MAIL_FROM}
mailersend.from.name=MicroShop

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
