server.port=${PORT:8007}

# MailerSend API Configuration
mailersend.api.url=https://api.mailersend.com/v1/email
mailersend.api.token=${MAILERSEND_API_TOKEN:mlsn.bd34a644d960b37aee8b724047415a314cb4e92102ee950e714aeb4dd30da185}
mailersend.from.email=${MAIL_FROM:MS_5PEmb8@test-51ndgwv5onqlzqx8.mlsender.net}
mailersend.from.name=MicroShop

# Thymeleaf Configuration
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
